### ISSUE TITLE
Extremely high CPU usage

### ISSUE THREAD

**Issue by rohanliston** [codegangsta/gin#53] opened 2015-01-06 11:57 UTC
When I run my Martini server through Gin, CPU usage goes through the roof - 85-100% on one core whilst sitting idle. If I run it without Gin, it's less than 1%. 

This has only started happening very recently. Ordinarily I'd suspect my own application code as the culprit, but the fact that it runs fine without Gin would indicate otherwise.

Running on an Ubuntu 12.04 Vagrant box on a Ubuntu 14.10 host.

**Comment by mariokostelac** [comment] 2015-04-23 16:13
How much file do you have in your path (recursively)?
It is possible that checking every 0.5seconds for change could be too often for you.
We should consider adding that as a cli parameter (or consider using file/dirwatchers for detecting changes).

@codegangsta do you want me to do that?

**Comment by johnsto** [comment] 2015-05-28 06:27
I have this problem as well, caused by one of those bloody `node_modules` directories behemoths where I run Gin. Makes my CPU go nuts after a while.

The ability to specify which directories should be watched would be a huge improvement!

**Comment by zippoxer** [comment] 2015-06-12 15:46
+1 for that. node_modules is a real pain

**Comment by kokizzu** [comment] 2015-07-22 11:00
+1 mine too '___')

```
$ find . | wc
  25589   27322 1452620
$ find . -type 'd' | wc
   2052    2173   84120
$ find . -iname '*.go' | wc
    144     144    3617
$ find .git | wc
     83      83    2374
$ find resources/ | wc # this folder will never ever be compiled
  24311   26044 1361828
$ find resources/ -type 'd' | wc
   1935    2056   78388
```

**Comment by mikegleasonjr** [comment] 2015-12-14 09:04
:+1: 

Is this project dead? Any alternatives?

**Comment by Vektah** [comment] 2015-12-14 09:11
https://github.com/codegangsta/gin/pull/83 fixes this issue. Sadly it its unmerged. 

I have a fork with that PR merged to master over at https://github.com/vektah/gin so it can be `go get github.com/vektah/gin`

**Comment by danawoodman** [comment] 2016-11-07 05:14
Bump...

**Comment by mikegleasonjr** [comment] 2016-11-07 11:14
I ended up using fswatch:

Not a shell guru so bare with me:

```
$ fswatch -0 -or --include ".*\.go$" --exclude ".*" . | xargs -0 -t -n 1 -I {} go install -v github.com/your/server &
$ fswatch -0 -or $GOPATH/bin/server | xargs -0 -t -n 1 -I {} sh -c 'killall server; $GOPATH/bin/server &> optional.log &' &
```

The first line rebuilds and installs your package when `*.go` changes, the second listens for a change of your installed server. (sometimes rebuilding does not yield a new binary, just a small optimization)

When I'm done, I `killall fswatch` and `killall server`. I was using [prm](https://github.com/eivind88/prm) anyway so I had startup and stop scripts at my disposition to automate that.

Lighter, more portable, faster, easier to run, etc..

**Comment by danawoodman** [comment] 2016-11-08 16:56
Thanks @mikegleasonjr!

**Comment by ibash** [comment] 2016-11-08 18:01
#83 is merged!

**Comment by danawoodman** [comment] 2016-11-08 18:04
Glad my bump resulted in so much awesome 👍 🍻 😄

**Comment by mikeifomin** [comment] 2017-04-24 18:15
I have excluded all huge directories with the `excludeDir` but still cpu is about 40% on idle .(

**Comment by mikeifomin** [comment] 2017-04-24 18:31
oops there was just a typo. All fixed.

**Comment by kokizzu** [comment] 2019-07-18 07:10
`--excludeDir unnecessaryDir` especially directories with node_modules helps a lot (14% cpu usage to 0-2%)

**Closed** 2019-07-24 02:31 UTC
